require("dotenv").config();
const express = require("express");
const cors = require("cors");
const rateLimit = require("express-rate-limit");
const compression = require("compression");

const coinRoutes = require("./routes/coinRoutes");
const stockRoutes = require("./routes/stockRoutes");
const newsRoutes = require("./routes/newsRoutes");
const searchRoutes = require("./routes/searchRoutes");
const priceRoutes = require("./routes/priceRoutes");
const assetsRoutes = require("./routes/assetsRoutes");
const aiRoutes = require("./routes/aiRoutes");
const dataRoutes = require("./routes/dataRoutes");
const watchlistRoutes = require("./routes/watchlistRoutes");
const alertRoutes = require("./routes/alertRoutes");
const pollRoutes = require("./routes/pollRoutes");
const portfolioRoutes = require("./routes/portfolioRoutes");
const userDataRoutes = require("./routes/userDataRoutes");
const dexscreenerRoutes = require("./routes/dexscreenerRoutes");
const jupiterRoutes = require("./routes/jupiterRoutes");
const raydiumRoutes = require("./routes/raydiumRoutes");
const pumpfunRoutes = require("./routes/pumpfunRoutes");
const jupiterLimitRoutes = require("./routes/jupiterLimitRoutes");
const jupiterDcaRoutes = require("./routes/jupiterDcaRoutes");
const errorHandler = require("./middleware/errorHandler");
const { cache } = require("./config/cache");
const { getAllStatuses: getCBStatuses } = require("./middleware/circuitBreaker");
const { initDatabase } = require("./config/database");

const app = express();
const PORT = process.env.PORT || 4000;
const startTime = Date.now();

app.set("trust proxy", 1);
app.use(cors({ origin: process.env.FRONTEND_URL || "http://localhost:3000" }));
app.use(compression());
app.use(express.json());

// Rate limiting
const aiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 30,
  standardHeaders: true,
  handler: (req, res) => {
    const retryAfter = Math.ceil((req.rateLimit?.resetTime - Date.now()) / 1000) || 60;
    res.status(429).json({ error: "Too many AI requests", retryAfter, message: `Please wait ${retryAfter} seconds before trying again` });
  },
});
const generalLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 300,
  standardHeaders: true,
  skip: (req) => req.path.includes("/stream/sse") || req.path === "/health",
  handler: (req, res) => {
    const retryAfter = Math.ceil((req.rateLimit?.resetTime - Date.now()) / 1000) || 60;
    res.status(429).json({ error: "Too many requests", retryAfter, message: `Please wait ${retryAfter} seconds` });
  },
});
app.use("/api/ai", aiLimiter);
app.use("/api", generalLimiter);

// Health check (enhanced)
app.get("/api/health", (req, res) => {
  const stats = cache.getStats ? cache.getStats() : {};
  res.json({
    status: "ok",
    timestamp: Date.now(),
    uptime: Math.floor((Date.now() - startTime) / 1000),
    cacheKeys: cache.keys ? cache.keys().length : 0,
    cacheHits: stats.hits || 0,
    cacheMisses: stats.misses || 0,
    circuitBreakers: getCBStatuses(),
  });
});

// Routes
app.use("/api/coins", coinRoutes);
app.use("/api/stocks", stockRoutes);
app.use("/api/news", newsRoutes);
app.use("/api/search", searchRoutes);
app.use("/api/prices", priceRoutes);
app.use("/api/ai", aiRoutes);
app.use("/api/assets", assetsRoutes);
app.use("/api/data", dataRoutes);
app.use("/api/watchlist", watchlistRoutes);
app.use("/api/alerts", alertRoutes);
app.use("/api/polls", pollRoutes);
app.use("/api/portfolio", portfolioRoutes);
app.use("/api/user-data", userDataRoutes);
app.use("/api/dex", dexscreenerRoutes);
app.use("/api/jup", jupiterRoutes);
app.use("/api/raydium", raydiumRoutes);
app.use("/api/pump", pumpfunRoutes);
app.use("/api/jup/limit", jupiterLimitRoutes);
app.use("/api/jup/dca", jupiterDcaRoutes);

// Error handler
app.use(errorHandler);

app.listen(PORT, () => {
  console.log(`[Server] Running on http://localhost:${PORT}`);
  console.log(`[Server] Pyth Hermes: ${process.env.PYTH_HERMES_URL}`);
  console.log(`[Server] CoinGecko: ${process.env.COINGECKO_API_URL}`);

  // Initialize MySQL (non-blocking, server works without it)
  initDatabase().then((ok) => {
    if (ok) console.log("[Server] MySQL persistence enabled");
    else console.log("[Server] Running without MySQL persistence");
  });

  // Cache warm-up: pre-fetch commonly requested data after startup
  setTimeout(async () => {
    console.log("[Warm-up] Pre-fetching market data...");
    try {
      const cgService = require("./services/coingeckoService");
      await Promise.allSettled([
        cgService.getGlobal(),
        cgService.getCoinsMarkets(1, 50),
        cgService.getTrending(),
      ]);
      console.log("[Warm-up] Market data cached successfully");
    } catch (err) {
      console.warn("[Warm-up] Failed:", err.message);
    }
  }, 2000);

  // Auto-generate digest every 2 hours (background, non-blocking)
  async function autoGenerateDigest() {
    try {
      const cgService = require("./services/coingeckoService");
      const newsService = require("./services/newsService");
      const dataService = require("./services/dataService");
      const aiService = require("./services/aiService");

      let marketData = "";
      const [global, topCoins, trending, news, yields] = await Promise.allSettled([
        cgService.getGlobal(),
        cgService.getCoinsMarkets(1, 50),
        cgService.getTrending(),
        newsService.getCryptoNews([], 10),
        dataService.getYields(10).catch(() => []),
      ]);

      const globalVal = global.status === "fulfilled" ? global.value : null;
      const topCoinsVal = topCoins.status === "fulfilled" ? topCoins.value : [];
      const trendingVal = trending.status === "fulfilled" ? trending.value : null;
      const newsVal = news.status === "fulfilled" ? news.value : [];
      const yieldsVal = yields.status === "fulfilled" ? yields.value : [];

      if (globalVal?.data) {
        marketData += `Global Market Cap: $${(globalVal.data.total_market_cap?.usd / 1e9).toFixed(2)}B\n`;
        marketData += `24h Volume: $${(globalVal.data.total_volume?.usd / 1e9).toFixed(2)}B\n`;
        marketData += `BTC Dominance: ${globalVal.data.market_cap_percentage?.btc?.toFixed(1)}%\n\n`;
      }
      if (topCoinsVal.length) {
        const gainers = [...topCoinsVal].sort((a, b) => (b.price_change_percentage_24h || 0) - (a.price_change_percentage_24h || 0)).slice(0, 5);
        const losers = [...topCoinsVal].sort((a, b) => (a.price_change_percentage_24h || 0) - (b.price_change_percentage_24h || 0)).slice(0, 5);
        marketData += `Top Gainers:\n${gainers.map(c => `  ${c.symbol.toUpperCase()}: ${c.price_change_percentage_24h?.toFixed(2)}%`).join("\n")}\n\n`;
        marketData += `Top Losers:\n${losers.map(c => `  ${c.symbol.toUpperCase()}: ${c.price_change_percentage_24h?.toFixed(2)}%`).join("\n")}\n\n`;
      }
      if (trendingVal?.coins) {
        marketData += `Trending: ${trendingVal.coins.slice(0, 5).map(c => c.item.name).join(", ")}\n\n`;
      }
      if (yieldsVal.length) {
        marketData += `Top DeFi Yields:\n${yieldsVal.slice(0, 5).map(y => `  ${y.project} (${y.chain}): ${y.apy?.toFixed(1)}% APY`).join("\n")}\n\n`;
      }
      if (newsVal.length) {
        marketData += `Headlines:\n${newsVal.slice(0, 8).map(n => `- [${n.source || "News"}] ${n.title}`).join("\n")}\n`;
      }

      // Pyth oracle confidence data
      try {
        const HERMES = "https://hermes.pyth.network";
        const pythFeeds = {
          BTC: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43",
          ETH: "ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace",
          SOL: "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d",
          XAU: "765d2ba906dbc32ca17cc11f5310a89e9ee1f6420508c63861f2f8ba4ee34bb2",
        };
        const idsParam = Object.values(pythFeeds).map(id => `ids[]=0x${id}`).join("&");
        const pythRes = await fetch(`${HERMES}/v2/updates/price/latest?${idsParam}`);
        if (pythRes.ok) {
          const pythData = await pythRes.json();
          if (pythData?.parsed?.length) {
            marketData += `\nPyth Oracle Confidence Data:\n`;
            for (const feed of pythData.parsed) {
              const p = feed.price;
              if (!p) continue;
              const expo = Number(p.expo);
              const price = Number(p.price) * Math.pow(10, expo);
              const conf = Number(p.conf) * Math.pow(10, expo);
              const confPct = price > 0 ? ((conf / price) * 100).toFixed(4) : "N/A";
              const sym = Object.entries(pythFeeds).find(([, id]) => id === feed.id)?.[0] || feed.id;
              marketData += `  ${sym}: $${price.toLocaleString()} (confidence: ±${confPct}%)\n`;
            }
          }
        }
      } catch (e) {
        // Pyth data is optional — continue without it
      }

      if (marketData) {
        await aiService.generateDigest(marketData);
        console.log("[AutoDigest] Digest generated successfully");
      }
    } catch (err) {
      console.warn("[AutoDigest] Failed:", err.message);
    }
  }

  // Generate first digest 30s after startup, then every 2 hours
  setTimeout(autoGenerateDigest, 30000);
  setInterval(autoGenerateDigest, 2 * 60 * 60 * 1000);
});
